[build]
  functions = "netlify/functions"

# Supaya URL fungsi jadi rapi: yoursite.netlify.app/api/auth
# alih-alih yoursite.netlify.app/.netlify/functions/auth
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
